-- =====================================================
-- QUERY 1: Pastikan tabel customers ada
-- =====================================================
CREATE TABLE IF NOT EXISTS public.customers (
  id bigint generated by default as identity not null,
  "customerName" text not null,
  email text not null,
  phone text not null,
  loyalty text not null default 'Bronze'::text,
  created_at timestamp with time zone not null default now(),
  constraint customers_pkey primary key (id)
) TABLESPACE pg_default;

-- =====================================================
-- QUERY 2: Nonaktifkan RLS untuk testing
-- =====================================================
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;

-- =====================================================
-- QUERY 3: Beri permission INSERT dan SELECT
-- =====================================================
GRANT INSERT ON public.customers TO anon;
GRANT INSERT ON public.customers TO authenticated;
GRANT SELECT ON public.customers TO anon;
GRANT SELECT ON public.customers TO authenticated;

-- =====================================================
-- QUERY 4: Cek data di tabel customers
-- =====================================================
SELECT * FROM public.customers;